### ISSUE TITLE
Perl broken in Mavericks

### ISSUE THREAD

**Issue by agneau** [xchataqua/xchataqua#127]
After upgrading from Mountain lion to Maverick, I can't use the perl plugin any more.
AutoLoad failed for: /Applications/XChat Azure.app/Contents/PlugIns/perl-mountainlion.bundle
Invalid Mac OS X bundle or required Mac OS X version is not satisfied .
Upgrading xchatazure  to 1.16.1 does not help
 It lokks like a plugin is lissing for Mavericks:
% ls -l  /Applications/XChat\ Azure.app/Contents/PlugIns
total 104
-rw-r--r--  1 root  wheel  13722 Aug  3 10:00 JBanner.rb
-rw-r--r--  1 root  wheel   7689 Aug  3 10:00 JFilter.rb
-rw-r--r--  1 root  wheel   2633 Aug  3 10:00 TimerSample.rb
-rw-r--r--  1 root  wheel  13361 Aug  3 10:00 alt_completion.pl
-rw-r--r--  1 root  wheel   2245 Aug  3 10:00 char_count.pl
-rwxr-xr-x  1 root  wheel    377 Aug  3 10:00 google.pl
drwxr-xr-x  3 root  wheel    102 Aug  3 10:27 perl-lion.bundle
drwxr-xr-x  3 root  wheel    102 Aug  3 10:27 perl-mountainlion.bundle
drwxr-xr-x  3 root  wheel    102 Aug  3 10:27 perl-snowleopard.bundle
drwxr-xr-x  3 root  wheel    102 Aug  3 10:27 python.bundle
drwxr-xr-x  3 root  wheel    102 Aug  3 10:27 ruby.bundle
drwxr-xr-x  3 root  wheel    102 Aug  3 10:27 tcl.bundle

**Comment by echristopherson** [comment]
Please reopen this. Perl is broken on 10.9 in 1.16.15 from the App Store. It shows:

     AutoLoad failed for: /Applications/XChat Azure.app/Contents/PlugIns/perl.bundle
      dlopen(/Applications/XChat Azure.app/Contents/PlugIns/perl.bundle/Contents/MacOS/perl, 10): Library not loaded: /System/Library/Perl/5.18/darwin-thread-multi-2level/CORE/libperl.dylib
        Referenced from: /Applications/XChat Azure.app/Contents/PlugIns/perl.bundle/Contents/MacOS/perl
        Reason: image not found


For whatever reason, it's looking specifically for Perl 5.18; my latest version in /System is 5.16.
