### ISSUE TITLE
error with unicode

### ISSUE THREAD

**Issue by p1mps** [xchataqua/xchataqua#128]
WIth the servers window opened if the user tries to close it a series of error windows pop up with this message:

Warning: "IRC (Latin/Unicode Hybrid)" character set is unknown. No conversion will be applied for network NAME_OF_SERVER.

where NAME_OF_SERVER is the name of the server in the list. For each of them a window pops up.

**Comment by p1mps** [comment]
Super old issue. We can close it

**Comment by youknowone** [comment]
thanks for checking the issue. is this solved now?

**Comment by p1mps** [comment]
Yep, I haven't seen the problem anymore :)
