### ISSUE TITLE
Crash after waking MBP

### ISSUE THREAD

**Issue by slintak** [xchataqua/xchataqua#14]
I am using Xchat Aqua on my 2010 MBP. I am usually conected to one server and one chanel. When I put computer to sleep (usually I forget to /quit from chanel, so Xchat is still conected) and when I wake up computer, Xchat crash.

I use latest version from Appstore with one plugin xdccq ( http://dev.jmoiron.net/xchat/ it is plugin written in Python ).

**Comment by youknowone** [comment]
The lastest version in App Store (1.17.4) is expected to fix this problem.
