### ISSUE TITLE
All plugins broken in Yosemite

### ISSUE THREAD

**Issue by rcombs** [xchataqua/xchataqua#149]
They all give errors like this when loaded:
```
  dlopen(/Applications/XChat Azure.app/Contents/PlugIns/perl.bundle/Contents/MacOS/perl, 10): Symbol not found: _xchat_command
    Referenced from: /Applications/XChat Azure.app/Contents/PlugIns/perl.bundle/Contents/MacOS/perl
    Expected in: flat namespace
   in /Applications/XChat Azure.app/Contents/PlugIns/perl.bundle/Contents/MacOS/perl
```

**Comment by arfNZ** [comment]
Hi - any update on when this might be sorted?  For me, it's TCL : AutoLoad failed for: /Applications/XChat Azure.app/Contents/PlugIns/tcl.bundle
  dlopen(/Applications/XChat Azure.app/Contents/PlugIns/tcl.bundle/Contents/MacOS/tcl, 10): Symbol not found: _xchat_command
    Referenced from: /Applications/XChat Azure.app/Contents/PlugIns/tcl.bundle/Contents/MacOS/tcl
    Expected in: flat namespace
   in /Applications/XChat Azure.app/Contents/PlugIns/tcl.bundle/Contents/MacOS/tcl

**Comment by Elyx0** [comment]
Same here, i've found https://github.com/xchataqua/xchataqua/issues/127 but the ZIP isn't available anymore

**Comment by arfNZ** [comment]
This ticket is coming up 4 months old and plugins are still completely broken .. anyone know if there's ANYTHING I  can do to make it functional with either tcl, ruby or perl plugins in the meantime?

**Comment by arfNZ** [comment]
ok .. I'll read the no response as "please find another IRC app that works and write this off to experience".

**Comment by youknowone** [comment]
Sorry, plugins are not usable currently. I had no time to fix problems.

**Comment by AwwCookies** [comment]
Do you plan on fixing it?

**Comment by youknowone** [comment]
Test build: https://github.com/xchataqua/xchataqua/releases/tag/appstore-1.16.3

Can you test this version?

**Comment by rcombs** [comment]
That build refuses to launch due to a bad code signature here.

**Comment by arfNZ** [comment]
Yes, crashes here too:

Process:               XChat Azure [9599]
Path:                  /Applications/XChat Azure.app/Contents/MacOS/XChat Azure
Identifier:            org.3rddev.xchatazure
Version:               ???
Code Type:             X86-64 (Native)
Parent Process:        ??? [1]
Responsible:           XChat Azure [9599]
User ID:               501

Date/Time:             2015-02-19 11:41:17.893 +1300
OS Version:            Mac OS X 10.10.2 (14C109)
Report Version:        11
Anonymous UUID:        9FE5B648-F128-7939-7D55-A4FF8225AD09

Sleep/Wake UUID:       65BDD76C-CCEE-4EA3-8127-18A28CB70554

Time Awake Since Boot: 130000 seconds
Time Since Wake:       10000 seconds

Crashed Thread:        0

Exception Type:        EXC_CRASH (Code Signature Invalid)
Exception Codes:       0x0000000000000000, 0x0000000000000000

**Comment by youknowone** [comment]
I am sorry. How about this? https://github.com/xchataqua/xchataqua/releases/download/appstore-1.16.3/XChat-Azure-1.16.3b.zip

**Comment by rcombs** [comment]
That fixed the signing, but I still get the same errors loading plugins.

**Comment by arfNZ** [comment]
Yep .. same here - sorry :)

**Comment by youknowone** [comment]
I am sorry for inconvinient. I think it is still signing problem.

https://github.com/xchataqua/xchataqua/releases/download/appstore-1.16.3/XChat-Azure-1.16.3c.zip

If it keeps to raise errors, tell me how did you made it.
I tested perl plugin with script google.pl ( https://github.com/xchataqua/xchataqua/blob/master/Mac/Plugins/perl/google.pl ), Using GUI plugin window in Main Menu -> Window -> Plugins.

**Comment by rcombs** [comment]
\o/ That build works here!

**Comment by youknowone** [comment]
1.16.3 distributions are deleted.

https://github.com/xchataqua/xchataqua/releases/tag/appstore-1.16.4

1.16.4 is waiting for review

**Comment by arfNZ** [comment]
thanks - looks much more promising :)    Can you confirm the location for scripts?  I assumed it's in the Plugins directory along with the bundles but they're not picked up .. what am I missing?

**Comment by youknowone** [comment]
1.16.5 again. It was rejected by other issue.

**Comment by rubahness** [comment]
Thank you!  My scripts are working again :)

**Comment by rcombs** [comment]
This is fixed now, so closing.
