### ISSUE TITLE
SASL

### ISSUE THREAD

**Issue by Sequoia** [xchataqua/xchataqua#164]
If there's a way to add SASL connection info to a network config I have not been able to figure out how to do it. Am I missing something?

Xchat linux does this.

**Comment by TingPing** [comment]
>Xchat linux does this.

It does not. You would have to use [cap_sasl.py](http://lwsitu.com/xchat/cap_sasl_xchat.pl).

If xchat-aqua ever makes a public release based upon HexChat it will be built in. (This is perhaps the client you used on Linux)

**Comment by Sequoia** [comment]
@TingPing ah yes you're right, I used hex chat. Is there a workaround for Aqua? Freenode requires sasl when I'm connected to my VPN.

**Comment by TingPing** [comment]
I already said the script for it.

**Comment by Sequoia** [comment]
Ah, I thought you meant I must have used that script on linux. Tyvm

**Comment by Sequoia** [comment]
@TingPing do you know who maintains that script? I keep getting
```
SASL is supported but there is no authentication information set for this network().
```
which appears to come from this line:
```
cap_out( "\cC05SASL is supported but there is no authentication information set for this network(\cC02".network_name()."\cC05)." );
```

So it looks like `network_name` is returning nothing or an empty string.
```pl
sub network_name {
	return lc get_info( "network" );
}
```
I'd attempt to debug if I knew more perl... do you know where `get_info` is defined or what it does?

**Comment by TingPing** [comment]
@Sequoia `/help sasl`

**Comment by Sequoia** [comment]
@TingPing I have looked there, yes . . . it does not explain how "server" is identified. For freenode the only SASL config that seems to work is one where I name the server simply `freenode`, not `irc.freenode.net` or `chat.freenode.net` or `*.freenode.net` or anything else.

I looked to see if I could find where the network name was coming from (or in this case not coming from)

from [plugin.c##xchat_get_info](https://github.com/xchataqua/xchat/blob/a8d7a79365d0fc2d7efbe7524f1daab626cdcc12/src/common/plugin.c#L1068)
```c
	case 0x6de15a2e:	/* network */
		return server_get_network (sess->server, FALSE);
```
which refers to [server.c](https://github.com/xchataqua/xchat/blob/a8d7a79365d0fc2d7efbe7524f1daab626cdcc12/src/common/server.c#L1921-L1930)
```c
char *
server_get_network (server *serv, gboolean fallback)
{
	if (serv->network)
		return ((ircnet *)serv->network)->name;

	if (fallback)
		return serv->servername;

	return NULL;
}
```

I'm still not clear on the exact mechanism that's being used to get the network "name", which seems to be the source of the trouble. Thoughts?

**Comment by TingPing** [comment]
@Sequoia The code you referenced is spot on. First it goes off the network list assuming thats set then it goes off of what the server said its name was in the 005 reply. So just always use the network list and it is pretty simple.

**Comment by Sequoia** [comment]
oooooh.... what the server is named LOCALLY. I get you.

So when my connection bounces & it switches from `irc.freenode.net` to `chat.freenode.net` . . . maybe xchat is no longer recognizing that we're still on the "FreeNode" network. I'll add `chat.freenode.net` to the FreeNode server list & see if that clears it up.  Thanks a lot!!

**Comment by TingPing** [comment]
> So when my connection bounces & it switches from irc.freenode.net to chat.freenode.net . . . maybe xchat is no longer recognizing that we're still on the "FreeNode" network. I'll add chat.freenode.net to the FreeNode server list & see if that clears it up. Thanks a lot!!

As long as you start the connection from the network list this should not bother it, but if you start the connection by address directly that would matter. (Well this applies to the real XChat I've not looked at this projects network list).

**Comment by Sequoia** [comment]
OK this may be an xchat bug then, will investigate further. thx
