### ISSUE TITLE
Build from scratch on Mavericks using XCode

### ISSUE THREAD

**Issue by challinan** [xchataqua/xchataqua#167]
I'd like to experiment with latest XChat Aqua as a developer.  Therefore, I wish to build XChat Aqua locally on my iMAC.  I am a Linux expert, but not familiar with XCode and building projects for MAC.  I will be  happy to prepare a document to include in the git repository for newbies like me who wish to build XChat Aqua from scratch.  What I need to understand is exactly what steps are required to successfully build and run XChat Aqua from XCode.  I don't see any howto docs nor any issues in the current crop of issues here on github.  

Here are the steps I use to try to build XChat Aqua.  I'm sure I'm missing some simple steps.

1) Open XCode, select "Check out existing project"
2) Enter https://github.com/xchataqua/xchataqua.git
3) Choose "master" branch, select which directory on my local machine clone to. (XChat will do the git clone by itself)
4) Chose location and click "Check Out"

Now XCode does the git clone operation and builds a project directory.

Already on checkout and opening the project I hit one issue:
Shell script invocation error: /Users/chris/sandbox/xchataqua/build/XChatAqua.build/Debug/Prebuild.build/Script-38F0696916382384002723AB.sh: line 12: cd: /Users/chris/sandbox/xchataqua/Pods: No such file or directory

Please note that I don't know what Pods is nor how to build it. :-P

The second issue I get is: Debug.xcconfig line 1: Unable to find included file "BuildNumber.xcconfig"

I think there are multiple projects but again, I'm not familiar with developing with XCode.

What are the steps that are required to get to a successful XChat Aqua build?

Any guidance will be much appreciated.  Thanks.  -Chris

**Comment by youknowone** [comment]
Hi. Cocoapods is a package manager for xcode. See https://cocoapods.org/

Basically, 
`sudo gem install cocoapods` for installing and `pod install` in xchataqua directory will help it.

**Comment by challinan** [comment]
Thanks youknowone!  That got me past the initial hurdles!  Here is the general process for building XChatAqua locally for your Mac.  Clone the repo, or better yet, let XCode do it for you.  If you are manually cloning the xchataqua, you must use --recursive, as follows:
`$ git clone --recursive --branch master git://github.com/xchataqua/xchataqua`

Once complete, you must execute the steps above to install the required dependencies:
`$ sudo gem install cocoapods`
`$ cd xchataqua`
`$ pod install`

Then open XCode on the workspace, not the project.  The easiest way is simply to use the MAC's open command from the project workspace:
`$ open XChatAqua.xcworkspace`

Once in XCode, you must select the "Prebuild" active scheme, and build that first.  The active scheme is found at the very top of the XCode window near the run controls.  
Select "Prebuild (XChatAqua project) -> "My Mac" and then build that first.  That builds the required dependencies, etc.

Once completed, then change the active scheme to "XChat Aqua -> My Mac, and then build.  This succeeded for me.

Now to figure out how to deploy it so I can run it without XCode. ;)

**Comment by youknowone** [comment]
Oh, thank you for sharing. I am sorry for you but I also found an article about it: https://github.com/xchataqua/xchataqua/wiki/HowToBuild

I forgot about it becasue it is very rarely heppening that someone ask about building the project. I will update it with your new tips ;) thanks!

**Comment by youknowone** [comment]
About deploying, I am using bash scripts in `tools` directory. `buildproduct.sh` creates a build for appstore from the source code. Open the script and remove last line not to generate pkg file or fix the signing information to sign it with other certificaiton.
