### ISSUE TITLE
How can I lookup/change/remove some key shortcuts?

### ISSUE THREAD

**Issue by item4** [xchataqua/xchataqua#174]
I don't want to leave chennel, but some command what I don't know cause part channel.

How can I lookup/change/remove some key shortcuts?

**Comment by youknowone** [comment]
It seems there is no key shortcut table. But "Leaving channel" is command+w and `Close` menu in `File` main menu. If you don't like to use the shortcut, you can change it in keyboard preference in OS X system preference.
