### ISSUE TITLE
compile error on Xcode 7.01

### ISSUE THREAD

**Issue by dhs227** [xchataqua/xchataqua#185]
With following error message: xchataqua/Pods/Headers/Private/FoundationExtension/CocoaExtension/NSAttributedString+Cocoa.h:34:19: error: typedef redefinition with different types ('NSInteger' (aka 'long') vs 'enum NSUnderlineStyle')

code synced to git master branch.

**Comment by youknowone** [comment]
The new version of FoundationExtension is released (1.1.0)

`pod update` will solve the problem
