### ISSUE TITLE
XChat Azure 1.17.0 crashes on wake from sleep every time on El Capitan

### ISSUE THREAD

**Issue by bigheadjer** [xchataqua/xchataqua#194]
Whenever I wake my MBP up from sleep, XChat Azure crashes.  Has been happening without fail since the update to 1.17.0.

The next time this happens, I will copy and paste the crash report.

**Comment by chrstphrchvz** [comment]
Here's a crash report I've gotten with 1.17.0, also on El Capitan. Happened on first try sleeping, so I'm assuming this is similar to what @bigheadjer wanted to upload (note that old crash reports can be retrieved from Applications > Utilities > Console.app under "User Diagnostic Reports", so we probably don't need to wait for the next crash).

Attachment was originally a .crash file.
[XChat Azure_2015-12-02-154603_cacbook.txt](https://github.com/xchataqua/xchataqua/files/50232/XChat.Azure_2015-12-02-154603_cacbook.txt)

**Comment by bigheadjer** [comment]
Thanks @chrstphrchvz I didn't know about that in Console before.  Here is my last crash (I sleep my Macbook many times during the day and not long after I posted this bug report the crash popups stopped appearing and I didn't know where to retrieve crash reports.

[XChat Azure_2015-12-01-191543_Meretseger.crash.txt](https://github.com/xchataqua/xchataqua/files/50249/XChat.Azure_2015-12-01-191543_Meretseger.crash.txt)

**Comment by youknowone** [comment]
Will this help the problem? https://github.com/xchataqua/xchataqua/releases/tag/appstore-1.17.1

**Comment by michielroding** [comment]
Same problem here on both an iMac and an MBP - XChat crashes on network changes and wake on sleep.

**Comment by CoreISP** [comment]
Latest version still suffers from this issue. Couldn't see when it was released, but I'm running latest from the app store.

**Comment by Lord-Kamina** [comment]
Am also suffering from the exact same issue; reproducible without fail when computer goes to sleep.
Here's my own crash report (as poster before, .crash renamed to .txt)

[XChat Azure_2015-12-21-153024_Anasas.txt](https://github.com/xchataqua/xchataqua/files/80596/XChat.Azure_2015-12-21-153024_Anasas.txt)

**Comment by youknowone** [comment]
It sounds this problem is related to SSL connection problem. when waking up from sleeping, it will be second connection of SSL. #2

**Comment by raudpats** [comment]
This crash is actually happening not on wake from sleep but on reconnect (with SSL). Usually network connection is up immediately so this feels like crash is on wake up. But if on some reason network connection is missing then XChat wakes up and starts to poll servers just fine until network connection is coming up and then shows few lines about coming up connection after what will crash.

**Comment by alberto56** [comment]
Here is a crash report of a crash that happened while the computer was awake, possibly related. (this tends to happen every 20 minutes or so).

[crash_no_sleep.txt](https://github.com/xchataqua/xchataqua/files/106910/crash_no_sleep.txt)

**Comment by youknowone** [comment]
1.17.2 may fix it: https://github.com/xchataqua/xchataqua/releases/tag/appstore-1.17.2

**Comment by youknowone** [comment]
The lastest version in App Store (1.17.4) is expected to fix this problem.
