### ISSUE TITLE
generate_header requires running from same directory

### ISSUE THREAD

**Issue by chrstphrchvz** [xchataqua/xchataqua#195]
The command on the wiki page HowToBuild shows running it directly as `xchat/plugins/perl/generate_header` (as contributed by @armada651), but this results in the following error:
```
~ $ cd git/xchataqua/
xchataqua $ xchat/plugins/perl/generate_header
Couldn't open 'lib/Xchat.pm':No such file or directory at xchat/plugins/perl/generate_header line 8.
```
whereas changing the directory to `xchat/plugins/perl` first and then running `./generate_header` runs without error.

Should HowToBuild be updated with this workaround, or should generate_header be updated to change to its own directory?

**Comment by Armada651** [comment]
I didn't contribute anything related to perl?

**Comment by chrstphrchvz** [comment]
@Armada651 Sorry, not trying to blame anyone here—simply found your edit "Add missing command to build perl plugin, needed for X-Chat Azure" on https://github.com/xchataqua/xchataqua/wiki/HowToBuild/_history

The specific file is actually from the xchat project, not xchataqua, and hasn't been touched since 2012; I may have filed this issue in the wrong place.

**Comment by youknowone** [comment]
I recommend to fix HowToBuild because the script is a part of xchat, not a part of xchat aqua. Big local patches will reduce compatibility.

**Comment by chrstphrchvz** [comment]
Edited HowToBuild to run generate_header in same directory:
```
(cd xchat/plugins/perl; ./generate_header)
```

**Comment by youknowone** [comment]
Thanks @chrstphrchvz :D
