### ISSUE TITLE
Build error: BanWindow.xib is missing?

### ISSUE THREAD

**Issue by dhs227** [xchataqua/xchataqua#198]
I got an error message during building process, says: 
> xchataqua/Mac/Resources/cs.lproj/: Interface Builder could not open the document BanWindow.xib" because it does not exist.

**Comment by dhs227** [comment]
Issue fixed after a clean rebuild. Closed.

**Comment by youknowone** [comment]
For future:

You must do 'Prebuild' target before real building.
