### ISSUE TITLE
Azure crashed when I try to open a new server

### ISSUE THREAD

**Issue by mitral** [xchataqua/xchataqua#200]
When I try to open a new server after having 2 active servers open, Azure instantly crashes.

**Comment by youknowone** [comment]
1.17.2 may fix it if it is SSL connection:

https://github.com/xchataqua/xchataqua/releases/tag/appstore-1.17.2

**Comment by youknowone** [comment]
The lastest version in App Store (1.17.4) is expected to fix this problem.
