### ISSUE TITLE
Check duplicted multiple SSL connections related issues

### ISSUE THREAD

**Issue by youknowone** [xchataqua/xchataqua#202]
#2 
#14 
#86 
#113 
#170 
#186 
#193 
#194 
#196 
#200 
#201

**Comment by wickerwaka** [comment]
This PR addresses some of these issues: https://github.com/xchataqua/xchat/pull/3

**Comment by bazzinotti** [comment]
I had some success using wickerwaka's PR - more details in my comment at xchataqua/xchat#3

**Comment by youknowone** [comment]
pre-release of 1.17.3: https://github.com/xchataqua/xchataqua/releases/tag/appstore-1.17.3

**Comment by youknowone** [comment]
pre-release of 1.17.4: https://github.com/xchataqua/xchataqua/releases/tag/appstore-1.17.4

**Comment by youknowone** [comment]
@wickerwaka your patch worked greatly and it is now working, thank you!
