### ISSUE TITLE
Connection failed. Error: (336134278) error:14090086:SSL routines:SSL3_GET_SERVER_CERTIFICATE:certificate verify failed

### ISSUE THREAD

**Issue by nbm077** [xchataqua/xchataqua#205]
I cannot connect to second instance of SSL using same certificate on same server.  I want to connect several times to the same server.  AFter the first connection , I get this error:

Connection failed. Error: (336134278) error:14090086:SSL routines:SSL3_GET_SERVER_CERTIFICATE:certificate verify failed

works with any other irc client i can connect multiple times using same certificate

Seems problem also happens for some reason even disconnects while connected.  It could be the "accept invalid ssl certificate" which I use.  it looks the same error as invalid certificate.

**Comment by nbm077** [comment]
works with any other irc client i can connect multiple times using same certificate

**Comment by nbm077** [comment]
fixed this by adding server public cert to openssl/cert.pem

**Comment by manjiki** [comment]
@nbm077 I tried added the certificate in OSX's keychain, to no avail. Would you please elaborate the steps to work around this?

**Comment by fafrd** [comment]
I'm also having this issue, the "Accept invalid SSL certificates" checkbox doesn't seem to work.

**Comment by youknowone** [comment]
1.17.4 is updated in App Store. Can you try this one?

**Comment by fafrd** [comment]
@youknowone Yep, this seems to have fixed it. thanks!

**Comment by youknowone** [comment]
Thanks for confirming :D
