### ISSUE TITLE
Cannot download from Apple App Store

### ISSUE THREAD

**Issue by Drizzt321** [xchataqua/xchataqua#238]
So, I can't download this from the Mac App Store because I don't (and won't create) an Apple ID. This is purely for work and I've used an older version which is awesome. However I don't ever intend to have an Apple ID as it's useless and pointless because I'm not going to buy anything from iTunes/App Store. Is there truly no way to download the latest version without going through the Mac App store?

**Comment by frlen** [comment]
It's available under releases right here on github...
https://github.com/xchataqua/xchataqua/releases

**Comment by Drizzt321** [comment]
Ah, thanks!
