### ISSUE TITLE
Clicking a link in Xchat Azure opens two tabs with the url in Chrome

### ISSUE THREAD

**Issue by Mirppc** [xchataqua/xchataqua#243]
Not a major breaking bug, yet whenever someone links a picture or a pastebin or any other url in an irc channel and one clicks to open it in a browser (Chrome) it opens two versions of that same url.

Xchat Azure is from the Mac Store.

http://paste.opensuse.org/81081335 version

**Comment by cunt-punt** [comment]
Noticing the same problem too
Version 1.18.1

**Comment by Mirppc** [comment]
Glad I am not alone.

**Comment by youknowone** [comment]
Thanks for the report.
The problem will be solved in the next release.
