### ISSUE TITLE
Please add a license to this repo

### ISSUE THREAD

**Issue by mbrukman** [xchataqua/xchataqua#270]
First, thank you for maintaining X-Chat Aqua (and Azure)!

Could you please add an explicit `LICENSE` file to the repo so that it's clear
under what terms the content is provided, and under what terms user
contributions are licensed?

Per [GitHub docs on licensing][github-docs-licensing]:

> [...] without a license, the default copyright laws apply, meaning that you
> retain all rights to your source code and no one may reproduce, distribute,
> or create derivative works from your work. If you're creating an open source
> project, we strongly encourage you to include an open source license.

Adding an explicit `LICENSE` file to the repo with a standard license also
allows GitHub to highlight the license on your repo with a [badge][github-blog-license-badge].

Thanks!

[github-docs-licensing]: https://help.github.com/articles/licensing-a-repository/#choosing-the-right-license
[github-blog-license-badge]: https://github.blog/2016-09-21-license-now-displayed-on-repository-overview/

**Comment by youknowone** [comment]
Thanks. It was not placed in the root directory due to careless restructuring of directories.
