### ISSUE TITLE
Can't connect to IPv6 server

### ISSUE THREAD

**Issue by baronerosso** [xchataqua/xchataqua#98]
--- Looking up 2001:5c0:1000:x::xxx..
 --- Unknown host. Maybe you misspelled it?
 --- Disconnected ().

**Comment by fenris** [comment]
can someone verify either this issue occurs in the latest version 1.16.2 ?

**Comment by baronerosso** [comment]
No issue with last version, the problem is Yosemite; if you haven’t native ipv6 but you have an ipv6 from gogo6/freenet6, you have tu copy your ipv6 and past it into Preferences, Network, Eternet, Advanced, TCP/IP, manual ipv6 configuration.

I don’t know if this is a Xchat problem, I have to do this with alls apps excluding Google Chrome.

> Il giorno 24/feb/2015, alle ore 21:21, fenris <notifications@github.com> ha scritto:
> 
> can someone verify either this issue occurs in the latest version 1.16.2 ?
> 
> —
> Reply to this email directly or view it on GitHub.
> 

--
Cordialmente, vostro

barone rosso
